name: Auto Release

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Configure Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
      
      - name: Create temporary branch
        run: |
          # Create a new branch for the version bump
          VERSION_BRANCH="chore/version-bump-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $VERSION_BRANCH
          echo "VERSION_BRANCH=$VERSION_BRANCH" >> $GITHUB_ENV
      
      - name: Create Release
        run: npx standard-version
      
      - name: Push changes to temporary branch
        run: |
          git push --set-upstream origin $VERSION_BRANCH
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): version bump [skip ci]"
          branch: ${{ env.VERSION_BRANCH }}
          base: main
          title: "chore(release): version bump [skip ci]"
          body: |
            This PR contains version bump generated by standard-version.
            
            Automated version bump as part of the release process.
          labels: |
            automated pr
            release
          draft: false 